const jobListings = [
  {
    companyName: "Amazon",
    logo: "https://img.logo.dev/amazon.com?token=pk_OsNJJVpJSACeklehixYtPQ&size=80&retina=true",
    daysPosted: 5,
    jobTitle: "Backend Engineer",
    jobTypes: ["Full-Time", "Senior Level"],
    salaryPerHour: 35,
  },
  {
    companyName: "Microsoft",
    logo: "https://img.logo.dev/cloud.microsoft?token=pk_OsNJJVpJSACeklehixYtPQ&size=80&retina=true",
    daysPosted: 3,
    jobTitle: "Full Stack Developer",
    jobTypes: ["Full-Time", "Mid-Level"],
    salaryPerHour: 30,
  },
  {
    companyName: "Google",
    logo: "https://img.logo.dev/google.com?token=pk_OsNJJVpJSACeklehixYtPQ&size=80&retina=true",
    daysPosted: 2,
    jobTitle: "Frontend Developer",
    jobTypes: ["Full-Time", "Mid-Level"],
    salaryPerHour: 32,
  },
  {
    companyName: "Netflix",
    logo: "https://img.logo.dev/netflix.com?token=pk_OsNJJVpJSACeklehixYtPQ&size=80&retina=true",
    daysPosted: 6,
    jobTitle: "UI Engineer",
    jobTypes: ["Part-Time", "Junior Level"],
    salaryPerHour: 22,
  },
  {
    companyName: "Tesla",
    logo: "https://img.logo.dev/tesla.com?token=pk_OsNJJVpJSACeklehixYtPQ&size=80&retina=true",
    daysPosted: 4,
    jobTitle: "Software Engineer",
    jobTypes: ["Full-Time", "Mid-Level"],
    salaryPerHour: 34,
  },
  {
    companyName: "IBM",
    logo: "https://img.logo.dev/ibm.com?token=pk_OsNJJVpJSACeklehixYtPQ&size=80&retina=true",
    daysPosted: 7,
    jobTitle: "Data Analyst",
    jobTypes: ["Part-Time", "Entry Level"],
    salaryPerHour: 20,
  },
  {
    companyName: "Intel",
    logo: "https://img.logo.dev/intel.com?token=pk_OsNJJVpJSACeklehixYtPQ&size=80&retina=true",
    daysPosted: 3,
    jobTitle: "Backend Developer",
    jobTypes: ["Full-Time", "Mid-Level"],
    salaryPerHour: 29,
  },
  {
    companyName: "Adobe",
    logo: "https://img.logo.dev/adobe.com?token=pk_OsNJJVpJSACeklehixYtPQ&size=80&retina=true",
    daysPosted: 1,
    jobTitle: "UI/UX Designer",
    jobTypes: ["Full-Time", "Senior Level"],
    salaryPerHour: 33,
  },
  {
    companyName: "Apple",
    logo: "https://img.logo.dev/apple.com?token=pk_OsNJJVpJSACeklehixYtPQ&size=80&retina=true",
    daysPosted: 2,
    jobTitle: "Mobile App Developer",
    jobTypes: ["Full-Time", "Mid-Level"],
    salaryPerHour: 28,
  },
  {
    companyName: "Meta",
    logo: "https://img.logo.dev/meta.com?token=pk_OsNJJVpJSACeklehixYtPQ&size=80&retina=true",
    daysPosted: 5,
    jobTitle: "React Developer",
    jobTypes: ["Full-Time", "Senior Level"],
    salaryPerHour: 31,
  }
];

export default jobListings;